
env:
  db:
    local:
      host: localhost
      port: 3306
      schema: GUARD
      username: root
      password: 1234
    dev:
      host: dev.avocadostudio.xyz
      port: 3306
      schema: GUARD
      username: root
      password: root

---

spring:
   profiles: default

migration:
   url: ${env.db.local.host}
   port: ${env.db.local.port}
   schema: ${env.db.local.schema}
   username: ${env.db.local.username}
   password: ${env.db.local.password}
   location: classpath:migration

---

spring:
   profiles: dev

migration:
   url: ${env.db.dev.host}
   port: ${env.db.dev.port}
   schema: ${env.db.dev.schema}
   username: ${env.db.dev.username}
   password: ${env.db.dev.password}
   location: classpath:migration
